### ISSUE TITLE
Availability of functions for generating initial conditions?

### ISSUE THREAD

**Issue by newalexander** [katiana22/surrogate-overparameterization#1]
Hello, and thanks for making this public; the paper is very interesting. For more general usability and extension of these results, would it be possible to upload the code you used to generate the initial conditions for the Brusselator solutions?

In addition, did you experiment with any spatial discretizations other than the `28 x 28` used in the paper?

**Comment by katiana22** [comment]
Hello,

Thank you for your interest in our code repository and I apologize for the late reply! 

You can generate the initial conditions using UQpy's 2D ```KarhunenLoeveExpansion2D``` class using as correlation function a squared exponential with the length scale parameter values provided in the manuscript: https://uqpyproject.readthedocs.io/en/latest/auto_examples/stochastic_processes/karhunen_loeve_2d/plot_karhunen_loeve_2d.html#sphx-glr-auto-examples-stochastic-processes-karhunen-loeve-2d-plot-karhunen-loeve-2d-py

Regarding your second question - we have not analyzed the sensitivity of the models to the PDE discretization since the 28x28 grid is sufficient for the studied problem, but it would be interesting to explore more complex applications that require more fine discretizations and high fidelity simulations.
